platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
inputs:
  - name: repo-name
  - name: folder-name
outputs:
  - name: image
params:
  CONTEXT: 
  DOCKERFILE:
run:
  path: build
