platform: linux
image_resource:
  type: docker-image
  source:
    repository: amazon/aws-cli
    tag: latest
inputs:
  - name: repo-git
outputs:
  - name: gmu
run:
  path: ./repo-git/ci/tasks/gmu/task.sh
