platform: linux
image_resource:
  type: docker-image
  source:
    repository: amazon/aws-cli
    tag: latest
inputs:
  - name: repo-name
outputs:
  - name: gmu-output
run:
  path: ./repo-name/ci/tasks/gmu/task.sh
