FROM onsdigital/jenkins-slave-sonar-scanner:3.2.0

LABEL uk.gov.ons.image.name="sonar"
LABEL uk.gov.ons.image.description="A Jenkins slave with sonar scanner Tool"
LABEL uk.gov.ons.image.version="3.2.0J11"

# Install Packages
RUN yum install -y java-11-openjdk && yum clean all

