FROM onsdigital/jenkins-slave-python:3.4.0

LABEL uk.gov.ons.image.name="python"
LABEL uk.gov.ons.image.description="A Jenkins slave with python Tool"
LABEL uk.gov.ons.image.version="3.4.0J11"

# Install Packages
RUN yum install -y java-11-openjdk && yum clean all

