FROM onsdigital/jenkins-slave-cm:3.0

LABEL uk.gov.ons.image.name="cm"
LABEL uk.gov.ons.image.description="A Jenkins slave with clerical matching Tools"
LABEL uk.gov.ons.image.version="3.0J11"

# Install Packages
RUN yum install -y java-11-openjdk && yum clean all

