version: '3'
services:
# TIER 1
  jenkins-slave-base:
    build: ./jenkins-slave-base
    image: onsdigital/jenkins-slave-base
# TIER 2
  scala_2-11-8:
    build: ./scala/2.11.8
    image: onsdigital/jenkins-slave-scala:2.11.8
    depends_on: 
      - jenkins-slave-base
  node_6-11-5:
    build: ./node/6.11.5
    image: onsdigital/jenkins-slave-node:6.11.5
    depends_on: 
      - jenkins-slave-base
  maven_3.2.5:
    build: ./maven/3.2.5
    image: onsdigital/jenkins-slave-maven:3.2.5
    depends_on: 
      - jenkins-slave-base
# TIER 3
  sbt_0-13-13:
    build: ./sbt/0.13.13
    image: onsdigital/jenkins-slave-sbt:0.13.13
    depends_on: 
      - scala_2-11-8