github_auth: &github_auth
  username: ((github_pat))
  password: x-oauth-basic

aws_auth: &aws_auth
  AWS_ACCESS_KEY_ID: ((ciashared_access_key_id_prod))
  AWS_SECRET_ACCESS_KEY: ((ciashared_access_key_secret_prod))

groups:
- name: all
  jobs:
  - "*"

- name: base_jenkins
  jobs:
  - jenkins-base

- name: base_jenkins_centos
  jobs:
  - jenkins-base-centos
  
- name: r
  jobs:
  - jenkins-r-*

resource_types:

- name: github-release
  type: registry-image
  source:
    repository: concourse/github-release-resource
    tag: latest

resources:
# The repo with our Dockerfile
- name: jenkins-git
  type: git
  icon: github
  source:
    uri: https://github.com/onsdigital/jenkins-build-envs
    #branch: cia-rhel-cicd
    branch: changing_image_target_from_docker_hub_to_github

- name: jenkins-base-container
  type: docker-image
  icon: docker
  source:
    repository: 013353241801.dkr.ecr.eu-west-2.amazonaws.com/jenkins-base
    aws_access_key_id: ((ciashared_access_key_id_prod))
    aws_secret_access_key: ((ciashared_access_key_secret_prod))

- name: jenkins-base-centos-container
  type: docker-image
  icon: docker
  source:
    repository: 013353241801.dkr.ecr.eu-west-2.amazonaws.com/jenkins-base-centos
    aws_access_key_id: ((ciashared_access_key_id_prod))
    aws_secret_access_key: ((ciashared_access_key_secret_prod))

- name: jenkins-r-container
  type: docker-image
  icon: docker
  source:
    repository: 013353241801.dkr.ecr.eu-west-2.amazonaws.com/jenkins-r
    aws_access_key_id: ((ciashared_access_key_id_prod))
    aws_secret_access_key: ((ciashared_access_key_secret_prod))


jobs:
- name: set-self
  plan: 
  - get: jenkins-git
    trigger: true
  - set_pipeline: self
    file : jenkins-git/ci/pipeline_ecr.yml
    var_files: 
      - jenkins-git/ci/env/variables.yml

#########
# jenkins-base container
#########
- name: jenkins-base
  plan:
  - get: jenkins-git
    passed: [set-self]
  - put: jenkins-base-container
    params: 
      build: jenkins-git/jenkins-base
      tag_file: jenkins-git/jenkins-base/VERSION

#########
# jenkins-base-centos container
#########
- name: jenkins-base-centos
  plan:
  - get: jenkins-git
    passed: [set-self]
  - put: jenkins-base-centos-container
    params: 
      build: jenkins-git/jenkins-base-centos
      tag_file: jenkins-git/jenkins-base-centos/VERSION


#########
# jenkins-r container
#########
- name: jenkins-r-4.4.1
  plan:
  - get: jenkins-git
    passed: [jenkins-base-centos]
    trigger: true
  - put: jenkins-r-container
    params: 
      build: jenkins-git/jenkins-r
      tag_file: jenkins-git/jenkins-r/VERSION
