github_auth: &github_auth
  username: ((github_pat))
  password: x-oauth-basic

aws_auth: &aws_auth
  AWS_ACCESS_KEY_ID: ((ciashared_access_key_id_prod))
  AWS_SECRET_ACCESS_KEY: ((ciashared_access_key_secret_prod))

slack_alert_message: &slack_alert_message
  text: |
        Jenkins Concourse job failed!
        Pipeline: $BUILD_PIPELINE_NAME
        Job: $BUILD_JOB_NAME
        Check it out:
        https://concourse.cicd-shared.aws.onsdigital.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

groups:
- name: all
  jobs:
  - "*"


- name: base_jenkins_centos
  jobs:
  - jenkins-base-centos
  
- name: r
  jobs:
  - jenkins-r-*

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
# The repo with our Dockerfiles 
- name: jenkins-git
  type: git
  icon: github
  source:
    uri: https://github.com/onsdigital/jenkins-build-envs
    #branch: cia-rhel-cicd
    branch: changing_image_target_from_docker_hub_to_github

- name: wednesday-build
  type: time
  icon: clock-outline
  source:
    start: 16:46
    stop: 17:16
    days: [Wednesday]

#- name: slack-alert
#  type: slack-notification
#  source:
#    url: ((slack_webhook)) # Comes from secret manager

- name: jenkins-base-centos
  type: docker-image
  icon: docker
  source:
    repository: 013353241801.dkr.ecr.eu-west-2.amazonaws.com/jenkins-base-centos
    aws_access_key_id: ((ciashared_access_key_id_prod))
    aws_secret_access_key: ((ciashared_access_key_secret_prod))

- name: jenkins-r-docker
  type: docker-image
  icon: docker
  source:
    repository: 013353241801.dkr.ecr.eu-west-2.amazonaws.com/jenkins-r
    aws_access_key_id: ((ciashared_access_key_id_prod))
    aws_secret_access_key: ((ciashared_access_key_secret_prod))

jobs:
- name: set-self
  plan: 
  - get: jenkins-git
    trigger: true
  - set_pipeline: self
    file : jenkins-git/ci/pipeline_ecr_2.yml
    var_files: 
      - jenkins-git/ci/env/variables.yml

- name: jenkins-base-centos
  plan:
  - get: wednesday-build
    trigger: true
  - get: jenkins-git
    passed: [set-self]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/ci/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/jenkins-base-centos
 #      on_failure:
 #       put: slack-alert
 #      params:
 #       <<: *slack_alert_message
  - put: jenkins-base-centos
    params:
      build: jenkins-git/jenkins-base-centos
      tag_file: jenkins-git/jenkins-base-centos/VERSION
#    on_failure:
#      put: slack-alert
#      params:
#        <<: *slack_alert_message

- name: jenkins-r-4.4.1
  plan:
  - get: jenkins-git
    passed: [jenkins-base-centos]
    trigger: true
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/ci/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/r
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
      BUILD_ARG_TOOL_VERSION: 4.4.1
#    on_failure:
#      put: slack-alert
#      params:
#        <<: *slack_alert_message
  - put: jenkins-r-docker
    params:
      image: image/image.tar
      version: 4.4.1
#    on_failure:
#      put: slack-alert
#      params:
#        <<: *slack_alert_message
