docker_auth: &docker_auth
  username: ((docker-username)) # These come from secrets manager
  password: ((docker-password))

github_auth: &github_auth
  username: ((github_pat))
  password: x-oauth-basic

slack_alert_message: &slack_alert_message
  text: |
        Jenkins Concourse job failed!
        Pipeline: $BUILD_PIPELINE_NAME
        Job: $BUILD_JOB_NAME
        Check it out:
        https://concourse.cicd-shared.aws.onsdigital.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

resources:
# The repo with our Dockerfile
- name: jenkins-git
  type: git
  icon: github
  source:
    uri: https://github.com/onsdigital/jenkins-build-envs
    branch: main

- name: wednesday-build
  type: time
  icon: clock-outline
  source:
    start: 05:00
    stop: 05:30
    days: Wednesday

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack_webhook)) # Comes from secret manager

- name: jenkins-base-docker
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: ((docker_organisation))/jenkins-base

- name: jenkins-scala-docker
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: ((docker_organisation))/jenkins-scala

- name: jenkins-sbt-docker
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: ((docker_organisation))/jenkins-sbt

- name: jenkins-cloud-foundry-cli-docker
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: ((docker_organisation))/jenkins-cloud-foundry-cli

- name: jenkins-node-docker
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: ((docker_organisation))/jenkins-node

- name: jenkins-cm-docker
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: ((docker_organisation))/jenkins-cm

- name: jenkins-gmu-docker
  type: registry-image
  icon: docker
  source:
    <<: *docker_auth
    repository: ((docker_organisation))/jenkins-gmu

jobs:
- name: jenkins-base
  plan:
  - get: wednesday-build
    trigger: true
  - get: jenkins-git
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/jenkins-base
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-base-docker
    params:
      image: image/image.tar
      version: ((jenkins_base_version))
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message


- name: jenkins-scala-2.11.8
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/scala
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
      BUILD_ARG_TOOL_VERSION: 2.11.8
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-scala-docker
    params:
      image: image/image.tar
      version: 2.11.8
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-scala-2.12.7
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/scala
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
      BUILD_ARG_TOOL_VERSION: 2.12.7
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-scala-docker
    params:
      image: image/image.tar
      version: 2.12.7
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-scala-2.12.12
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/scala
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
      BUILD_ARG_TOOL_VERSION: 2.12.12
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-scala-docker
    params:
      image: image/image.tar
      version: 2.12.12
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-scala-2.13.4
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/scala
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
      BUILD_ARG_TOOL_VERSION: 2.13.4
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-scala-docker
    params:
      image: image/image.tar
      version: 2.13.4
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-sbt-1.2.4
  plan:
  - get: jenkins-git
    passed: [jenkins-scala-2.12.7]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/sbt
      BUILD_ARG_PARENT_VERSION: 2.12.7
      BUILD_ARG_TOOL_VERSION: 1.2.4
      BUILD_ARG_MAJOR_MINOR_VERSION: 1.1
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-sbt-docker
    params:
      image: image/image.tar
      version: 1.2.4
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-sbt-0.13.13
  plan:
  - get: jenkins-git
    passed: [jenkins-scala-2.11.8]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/sbt
      BUILD_ARG_PARENT_VERSION: 2.11.8
      BUILD_ARG_TOOL_VERSION: 0.13.13
      BUILD_ARG_MAJOR_MINOR_VERSION: 0.13
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-sbt-docker
    params:
      image: image/image.tar
      version: 0.13.13
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-cloud-foundry-cli
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/cloud-foundry
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-cloud-foundry-cli-docker
    params:
      image: image/image.tar
      version: 1.0.0
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-node-6.11.5
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/node
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
      BUILD_ARG_TOOL_VERSION: v6.11.5
      BUILD_ARG_SHA256: fffd25c9e9b6d2235e97ba8be1dd6ea5f31e32ea445c5cc704ca84ef44db66c1
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-node-docker
    params:
      image: image/image.tar
      version: 6.11.5
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-node-9.9.0
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/node
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
      BUILD_ARG_TOOL_VERSION: v9.9.0
      BUILD_ARG_SHA256: 887cb4db6207f303b5ba15b6e15298f19d288fce2064e8caa7bb7cae170cbe85
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-node-docker
    params:
      image: image/image.tar
      version: 9.9.0
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-node-12.16.2
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/node
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
      BUILD_ARG_TOOL_VERSION: v12.16.2
      BUILD_ARG_SHA256: ffc92b8d9f53a10a2a734c93e78a3be74af7b0034bddd6f034a700c430eb94c1
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-node-docker
    params:
      image: image/image.tar
      version: 12.16.2
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-node-15.3.0
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/node
      BUILD_ARG_PARENT_VERSION: ((jenkins_base_version))
      BUILD_ARG_TOOL_VERSION: v15.3.0
      BUILD_ARG_SHA256: c3f6c64d98e623c783b7de7580365be74d8a2dba87529447ae66061609b5d0ec
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-node-docker
    params:
      image: image/image.tar
      version: 15.3.0
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-cm-1.0.0
  plan:
  - get: jenkins-git
    passed: [jenkins-node-12.16.2]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/cm
      BUILD_ARG_TOOL_VERSION: 4.0.1
      BUILD_ARG_PARENT_VERSION: 12.16.2  
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-cm-docker
    params:
      image: image/image.tar
      version: 1.0.0
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-cm-2.0.0
  plan:
  - get: jenkins-git
    passed: [jenkins-node-15.3.0]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/cm
      BUILD_ARG_TOOL_VERSION: 4.0.1
      BUILD_ARG_PARENT_VERSION: 15.3.0  
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-cm-docker
    params:
      image: image/image.tar
      version: 2.0.0
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message

- name: jenkins-gmu
  plan:
  - get: jenkins-git
    passed: [jenkins-base]
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    file: jenkins-git/packer_build.yml
    input_mapping:
      repo-name: jenkins-git
    params:
      CONTEXT: repo-name/gmu
      BUILD_ARG_TOOL_VERSION: ((jenkins_base_version))
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message
  - put: jenkins-gmu-docker
    params:
      image: image/image.tar
      version: latest
    on_failure:
      put: slack-alert
      params:
        <<: *slack_alert_message


