name: ci

on:
  push:
    branches: [ master ]
    schedule:
      - cron: '0 0 * * *' #Run at the end of every day
# When working on a pull-request uncomment the below to be able to test out changes in your PR branch
#  pull_request:
#    branches: [ github-actions-ci ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build all images
        run: docker-compose build --force-rm  --pull --progress=auto

      - name: Push all images
        run: docker-compose push